In [13]:
# NumPy Joining Array
# package import 
import numpy as np
arr_1=np.array([1,2,3])
arr_2=np.array([4,5,6])
# concatenate on two array
arr=np.concatenate((arr_1 , arr_2))
print("concatenate two array :",arr)
                            # output :concatenate two array : [1 2 3 4 5 6]

# Join two 2-D arrays along rows (axis=1)
arr_1=np.array([[1,2,3],[3,4,5]])
arr_2=np.array([[4,5,6],[6,7,8]])
arr=np.concatenate((arr_1,arr_2),axis=1)
print("Join two 2-D arrays along rows :",arr)
                                # output :Join two 2-D arrays along rows : [[1 2 3 4 5 6]
                                #                                          [3 4 5 6 7 8]]

# Joining Arrays Using Stack Functions
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis
arr_1=np.array([1,2,3])
arr_2=np.array([4,5,6])
arr=np.stack((arr_1 , arr_2),axis=1)
print("Joining Arrays Using Stack Functions :",arr)
                                # output :Joining Arrays Using Stack Functions : [[1 4]
                                #                                                [2 5]
                                #                                                [3 6]]
# Stacking Along Rows
# NumPy provides a helper function: hstack() to stack along rows.
arr_1=np.array([[1,2,3],[4,5,6]])
arr_2=np.array([[7,8,9],[10,11,12]])
arr=np.hstack((arr_1 , arr_2))
print("helper function: hstack :",arr)
                                # output :helper function: hstack : [[ 1  2  3  7  8  9]
                                                                 #  [ 4  5  6 10 11 12]]

# Stacking Along Columns
# NumPy provides a helper function: vstack()  to stack along columns
arr_1=np.array([1,2,3])
arr_2=np.array([4,5,6])
arr=np.vstack((arr_1 , arr_2))
print("helper function: vstack :",arr)

# Stacking Along Height (depth)
# NumPy provides a helper function: dstack() to stack along height, which is the same as depth

# Stacking Along Height (depth)
# NumPy provides a helper function: dstack() to stack along height, which is the same as depth
arr_1=np.array([[1,2,3],[6,7,8]])
arr_2=np.array([[4,5,6],[10,11,12]])
arr=np.dstack((arr_1 , arr_2))
print("Stacking Along Height :",arr)
                                            # output :Stacking Along Height : [[[ 1  4]
                                            #                                 [ 2  5]
                                            #                                 [ 3  6]]

                                            #                                 [[ 6 10]
                                            #                                 [ 7 11]
                                            #                                 [ 8 12]]]





concatenate two array : [1 2 3 4 5 6]
Join two 2-D arrays along rows : [[1 2 3 4 5 6]
 [3 4 5 6 7 8]]
Joining Arrays Using Stack Functions : [[1 4]
 [2 5]
 [3 6]]
helper function: hstack : [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
helper function: vstack : [[1 2 3]
 [4 5 6]]
Stacking Along Height : [[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 6 10]
  [ 7 11]
  [ 8 12]]]


In [26]:
# NumPy Splitting Array
arr=np.array([1,2,3,4,5,6,7,8,9,10])
new_arr=np.array_split(arr,2)
print("NumPy Splitting Array",new_arr)
                    # output : NumPy Splitting Array [array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

# NumPy Searching Arrays
arr=np.array([1,2,3,4,5,6,7,8,9,10])
find_index_of_number=np.where(arr==4)
print("NumPy Searching Arrays",find_index_of_number)
                    # output :NumPy Searching Arrays (array([3]),)
# NumPy Sorting Arrays
arr=np.array([10,9,8,7,6,5,4,3,2,1])
sort_array=np.sort(arr)
print("NumPy Sorting Arrays",sort_array)
                    # output :NumPy Sorting Arrays [ 1  2  3  4  5  6  7  8  9 10]

# NumPy Filter Array
arr=np.array([20,30,40,50,60,70,80])
filter_elements=[]
for ele in arr:
    if ele>30:
        filter_elements.append(True)
    else:
        filter_elements.append(False)
new_arr=arr[filter_elements]
print("filter_elements :",new_arr)
print(" conditions :",filter_elements)
                                # output :filter_elements : [40 50 60 70 80]
                                        #  conditions : [False, False, True, True, True, True, True]

NumPy Splitting Array [array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
NumPy Searching Arrays (array([3]),)
NumPy Sorting Arrays [ 1  2  3  4  5  6  7  8  9 10]
filter_elements : [40 50 60 70 80]
 conditions : [False, False, True, True, True, True, True]
