In [13]:
# NumPy Array Copy vs View
# package import 
import numpy as np
arr=np.array([1,2,3,4,5])
# Make a copy, change the original array, and display both arrays
x=arr.copy()
arr[0]=22
print("arr it as have modified first index",arr)
print("in x it as keep the original values :",x)
                    # output : arr it as have modified first index [22  2  3  4  5]
                    # output : in x it as keep the original values : [1 2 3 4 5]

# Make a view, change the view, and display both arrays
arr=np.array([22,33,44,55])
x=arr.view()
x[0]=1000
print("output of arr :",arr)
print(" output of x :",x)
                    # output of arr : [1000   33   44   55]
                    #  output of x : [1000   33   44   55]

# NumPy Array Shape
arr=np.array([[1,2,4,5],[3,5,6,7]])
print("shape of arr",arr.shape)
                    # output :shape of arr (2, 4)

# Create an array with 5 dimensions
arr=np.array([2,3,4,6,7,8],ndmin=5)
print("shape of arr",arr.shape)

# NumPy Array Reshaping
arr=np.array([1,2,3,4,5,6,7,89,1,0])
# Reshape From 1-D to 2-D
print("reshape of arr",arr.reshape(5,2))
                                # output :reshape of arr [[ 1  2]
                                                    #  [ 3  4]
                                                    #  [ 5  6]
                                                    #  [ 7 89]
                                                    #  [ 1  0]]

# Reshape From 1-D to 3-D
arr=np.array([1,3,4,57,8,9,0,7,4,5,87,99])
print("reshape of arr :",arr.reshape(4,3))
# output :reshape of arr : [[ 1  3  4]
                         # [57  8  9]
                         # [ 0  7  4]
                         # [ 5 87 99]]


arr it as have modified first index [22  2  3  4  5]
in x it as keep the original values : [1 2 3 4 5]
output of arr : [1000   33   44   55]
 output of x : [1000   33   44   55]
shape of arr (2, 4)
shape of arr (1, 1, 1, 1, 6)
reshape of arr [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7 89]
 [ 1  0]]
reshape of arr : [[ 1  3  4]
 [57  8  9]
 [ 0  7  4]
 [ 5 87 99]]
